name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
depend: []
api-version: 1.13

main: ${mainClass}
load: STARTUP

softdepend: [WorldEdit, PlaceholderAPI, MVdWPlaceholderAPI, WildStacker, EpicSpawners, UltimateStacker, MergedSpawner, Vault, Multiverse-Core, Essentials, EssentialsChat, ChatManager, DeluxeChat]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command