name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
depend: [ProtocolLib, Vault, WorldEdit]
api-version: 1.13

main: ${mainClass}
load: STARTUP

softdepend: [AdvancedSpawners, EpicSpawners, Essentials, EssentialsSpawn, MergedSpawner, Multiverse-Core, MVdWPlaceholderAPI, PlaceholderAPI, UltimateStacker, WildStacker, WorldEdit]
commands:
  island:
    aliases: ["is", "${project.name}"]
    description: Main plugin command