name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
depend: [Vault]
api-version: 1.13

main: ${mainClass}
load: STARTUP

softdepend: [EpicSpawners, Essentials, EssentialsSpawn, MergedSpawner, MVdWPlaceholderAPI, Multiverse-Core, PlaceholderAPI, UltimateStacker, WildStacker, WorldEdit]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command